platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/builder}

params:
  REPOSITORY: concourse/dev
  DOCKERFILE: concourse/ci/dockerfiles/dev/Dockerfile

inputs:
- name: concourse
- name: gdn
- name: fly-linux
- name: fly-windows
- name: fly-darwin
- name: bosh-io-release-resource
- name: bosh-io-stemcell-resource
- name: cf-resource
- name: docker-image-resource
- name: git-resource
- name: github-release-resource
- name: hg-resource
- name: mock-resource
- name: pool-resource
- name: registry-image-resource
- name: s3-resource
- name: semver-resource
- name: time-resource
- name: tracker-resource

outputs:
- name: image

run: {path: build}
